apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: k8s-deployment
spec:
  selector:
    matchLabels:
      app: sba-k8s
  replicas: 3 
  template:
    metadata:
      labels:
        app: sba-k8s
    spec:
      containers:
      - name: k8s-container 
        image: buildapp/k8s-webapp
        ports:
        - containerPort: 5000
---

apiVersion: v1
kind: Service
metadata:
  name: k8s-service
spec:
  type: NodePort
  selector:
    app: sba-k8s
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 32000
