apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: load-balancer-sba-k8s
  name: sba-k8s
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: load-balancer-sba-k8s
  template:
    metadata:
      labels:
        app.kubernetes.io/name: load-balancer-sba-k8s
    spec:
      containers:
      - image: sba-k8s:latest
        name: sba-k8s
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        - name: KLAUS_PORT
          value: "8080"
